### ISSUE TITLE
[Enhancement] Add support for check of one endpoint only

### ISSUE THREAD

**Issue by the-Blue-Falcon** [0xInfection/XSRFProbe#14]
Hi again,

Thank you again for your awesome work. However, it is a bit of crappy for XSRFProbe to scan the whole website and crawl and submit tokens/forms and other stuff. But it would be good if we could supply an URL and make XSRFProbe test the endpoint exclusively for CSRF vulnerabilities.

**Comment by 0xInfection** [comment]
Hmm I was thinking of implementing this for quite a while.

__Update:__ I am working on this feature. 😉
