### ISSUE TITLE
[Bug] => Improper Windows Output

### ISSUE THREAD

**Issue by 0xInfection** [0xInfection/XSRFProbe#22]
#### Describe the bug
When the tool is run on windows based systems, the output printed on terminal is uneven and improper without any proper hashmarks.

#### Command You Used
No specific command. Reproducible on any command on windows based systems.

#### Terminal Output
```No persistent session cookies identified on GET Type Requests!
Proceeding to test cookie persistence on POST Requests...
No persistent session cookies identified upon POST Requests!
 [+] Endpoint might be  NOT VULNERABLE  to CSRF attacks!
 [+] Detected :  No Persistent Cookies
Proceeding to test cookie persistence via User-Agent Alteration...
Setting custom generic headers...
Using User-Agent : Chrome on Windows 8.1
Value : Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
Processing the GET Request...
```

#### Potential cause or fix
It can be easily solved by escaping the ANSI sequnces with null. PR #23 fixes it. :)

#### Environment:
- OS: Windows 10
- Python version: v3.7

#### Some Questions

- [x] I am using the latest version of XSFRProbe.
- [x] I installed the dependecies using `pip3` instead of `pip`.
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

#### Other stuff
Neh.

**Comment by iDuronto** [comment]
This has been fixed right?
