### ISSUE TITLE
[Bug] => No cookie return type exception

### ISSUE THREAD

**Issue by iDuronto** [0xInfection/XSRFProbe#31]
#### Describe the bug
When a site does not set cookies, XSRFProbe stops execution due to absence of missing cookies which return `Nonetype` thus causing a raw unhandled exception out of the blue.

#### Command You Used
```
python3 xsrfprobe.py -u http://hack-yourself-first.com/Account/changePassword
```

#### Full Stack Trace Error
```
Traceback (most recent call last):
  File "xsrfprobe.py", line 15, in <module>
    main.Engine()  # start the Scanner Engine ;)
  File "C:\Users\user\Videos\xsrfprobe\xsrfprobe\core\main.py", line 143, in Engine
    Cookie(url, r1)
  File "C:\Users\user\Videos\xsrfprobe\xsrfprobe\modules\Cookie.py", line 33, in Cookie
    Persistence(url, request)
  File "C:\Users\user\Videos\xsrfprobe\xsrfprobe\modules\Persistence.py", line 122, in Persistence
    VulnLogger(url, 'Persistent Session Cookies Found.', '[i] Cookie: '+req.headers.get('Set-Cookie'))
TypeError: can only concatenate str (not "NoneType") to str
```

#### Potential cause or fix
Maybe handling the error properly?

#### Environment:
- OS: Kali Rolling 2018.3
- Python version: v3.7

#### Some Questions

- [x] I am using the latest version of XSFRProbe.
- [x] I installed the dependecies using `pip3` instead of `pip`.
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

#### Other stuff
[Something else you want the author to know?]

**Comment by iDuronto** [comment]
@sumgro, do you recall a similar bug?

**Comment by sumgr0** [comment]
Yes, this is the same one.

I'm still getting this post the update:
```
Traceback (most recent call last):
  File "xsrfprobe.py", line 13, in <module>
    main.Engine()  # start the Scanner Engine ;)
  File "/root/PenTest/Audit/XSRFProbe/core/main.py", line 143, in Engine
    Cookie(url, r1)
  File "/root/PenTest/Audit/XSRFProbe/modules/Cookie.py", line 33, in Cookie
    Persistence(url, request)
  File "/root/PenTest/Audit/XSRFProbe/modules/Persistence.py", line 122, in Persistence
    VulnLogger(url, 'Persistent Session Cookies Found.', '[i] Cookie: '+req.headers.get('Set-Cookie'))
TypeError: must be str, not NoneType
```

**Comment by 0xInfection** [comment]
I have pushed a stable code right now to the [Fixing-#31](https://github.com/0xInfection/XSRFProbe/tree/Fixing-%2331) branch. Can anyone test that branch to see if the error has been resolved?

Have a look at #32.

**Comment by iDuronto** [comment]
Woah, this is why I admire him. Within a single hour he managed to fix the bug, works for me. Awesome work @0xInfection.

You are fast as lightning.

**Comment by sumgr0** [comment]
Salute...this is fixed now. Awesome. Thanks @0xInfection
