### ISSUE TITLE
[N/A] => Tested

### ISSUE THREAD

**Issue by vulnz** [0xInfection/XSRFProbe#4]
Tested in in websites with 100% CSRF vuln.
Can you please provide website where it gives positive result?

**Comment by 0xInfection** [comment]
Presently XSRFProbe has only methods for detecting form based CSRFs. If you can hand me the website (maybe email me) where you've got the 100% vulnerability then I guess I can work this out to detect specifically the type of CSRF prevaling there.

**Comment by 0xInfection** [comment]
No expected cooperation from your side. Hence closed.
