### ISSUE TITLE
No console output after running in Windows 10 cmd window.

### ISSUE THREAD

**Issue by wadim-al** [0xInfection/XSRFProbe#47]
#### Describe the bug
No console output after running in Windows 10 x64 2004 cmd window with Python 3.7.8.

#### Command You Used
pip3 install xsrfprobe
C:\Python37\python C:\Python37\Lib\site-packages\xsrfprobe\xsrfprobe.py --help
py -3 xsrfprobe.py --help
python xsrfprobe.py --help
python3 xsrfprobe.py --help

![cmd-2020-08-30-17-40-04](https://user-images.githubusercontent.com/29713984/91661942-df204380-eae7-11ea-990f-1bb2237de5aa.png)

#### Full Stack Trace Error
None

#### Potential cause or fix
Googling suggests setting  Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\InheritConsoleHandles to 0, 1 or deleting the key, but this doesn't help.

#### Environment:
- __OS__: Windows 10 x64 2004
- __Python version__: 3.7.8

#### Some Questions

- [x] I am using the latest version of XSFRProbe.
- [x] I installed the dependecies using `pip3` instead of `pip`.
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

#### Other stuff
[Something else you want the author to know?]

**Comment by 0xInfection** [comment]
Um, I'm not sure what might be going wrong here since I left using Windows for quite few years, but from the looks of it, if the `site-packages` directory is within the `PATH` of your system environment variables, you should be able to use `xsrfprobe --help` directly from anywhere irrespective of cwd, since you installed the tool using `pip`.

**Comment by wadim-al** [comment]
Have tried with the Python which installs from MS Store: now even after adding xsrfprobe.py parent dir to PATH python can't find it. Directly invoking the app doesn't work too. See the log.txt

[log.txt](https://github.com/0xInfection/XSRFProbe/files/5149328/log.txt)

**Comment by wadim-al** [comment]
Uninstalled Python from the MS Store, uninstalled other pythons on the system, cleaned the PATH.

After reinstalling Official Python 3.7.9 x64 with full installer results are empty too:

```
C:\Users\VZ\Desktop\WORK>py -3 C:\Python37\Lib\site-packages\xsrfprobe\xsrfprobe.py --help

C:\Users\VZ\Desktop\WORK>python C:\Python37\Lib\site-packages\xsrfprobe\xsrfprobe.py --help

```
Do you have any idea where to ask for help if the mentioned registry tweak doesn't do anything?

**Comment by wadim-al** [comment]
Now I've tested if my configuration is able to run --help in other .py scanner:

```
C:\Users\VZ>py -3 C:\Python37\Lib\site-packages\xsrfprobe\xsrfprobe.py --help

C:\Users\VZ>python C:\Python37\Lib\site-packages\xsrfprobe\xsrfprobe.py --help

C:\Users\VZ>pause
Press any key to continue . . .

C:\Users\VZ>python F:\sec\XSStrike-3.1.5\xsstrike.py --help

        XSStrike v3.1.4

usage: xsstrike.py [-h] [-u TARGET] [--data PARAMDATA] [-e ENCODE] [--fuzzer]
                   [--update] [--timeout TIMEOUT] [--proxy] [--params]
                   [--crawl] [--json] [--path] [--seeds ARGS_SEEDS]
                   [-f ARGS_FILE] [-l LEVEL] [--headers [ADD_HEADERS]]
                   [-t THREADCOUNT] [-d DELAY] [--skip] [--skip-dom] [--blind]
                   [--console-log-level {DEBUG,INFO,RUN,GOOD,WARNING,ERROR,CRITICAL,VULN}]
                   [--file-log-level {DEBUG,INFO,RUN,GOOD,WARNING,ERROR,CRITICAL,VULN}]
                   [--log-file LOG_FILE]
...
```
Other Python script gave out the output.

Also, installing manually by "python setup.py install" doesn't allow to use the xsrfprobe command directly, but this is maybe for another issue.

Also, installing in kali-rolling with pip also doesn't allow xsrfprobe to be valid command and doesn't provide any output.

Command used: python3 /home/vz/.local/lib/python3.8/site-packages/xsrfprobe/xsrfprobe.py --help

**Comment by 0xInfection** [comment]
Hmm, from the looks of your `log.txt` file, I can clearly see that the binary file directory of the python installation is not within your PATH. So I guess you can add `C:\Python{your_version}\Scripts` to your path and then just run `xsrfprobe --help`, or simply select the checkbox saying `Add Python 3.7 to PATH` before installing Python with the executable. Always [follow the official guide](https://docs.python.org/3/using/windows.html) when installing Python. 

For the kali, I guess you just have to use `sudo` nothing else. Or maybe you can run `python3 -m pip install xsrfprobe`, that should work.

If you try to run the file directly, it is not possible since XSRFProbe is not built in that manner, it is supposed to be a package rather than a runnable file. So you will need the compiled binary to run it.

**Comment by wadim-al** [comment]
After installing standalone Python, it added itself to PATH correctly, and yes I did restart the system and cleaned up all other Pythons, disabled Win10 python redirection binary aliases and rechecked the registry key from Google. Still can't run as simple 'xsrfprobe --help'

This was the output that shows PATH, fact of installation of xsrfprobe and result of attempt to run help:

```
C:\Users\VZ>echo %PATH%
C:\Python37\Scripts\;C:\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;D:\Program Files\ffmpeg\bin;D:\Program Files\platform-tools;C:\Program Files (x86)\WinMerge;C:\Program Files\dotnet\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Users\VZ\AppData\Local\Microsoft\WindowsApps;C:\Users\VZ\.dotnet\tools;C:\Users\VZ\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\VZ\AppData\Roaming\npm

C:\Users\VZ>pip3 install xsrfprobe
Requirement already satisfied: xsrfprobe in c:\python37\lib\site-packages\xsrfprobe-2.3.0-py3.7.egg (2.3.0)
Requirement already satisfied: requests in c:\python37\lib\site-packages (from xsrfprobe) (2.24.0)
Requirement already satisfied: bs4 in c:\python37\lib\site-packages (from xsrfprobe) (0.0.1)
Requirement already satisfied: stringdist in c:\python37\lib\site-packages (from xsrfprobe) (1.0.9)
Requirement already satisfied: tld in c:\python37\lib\site-packages (from xsrfprobe) (0.12.2)
Requirement already satisfied: yattag in c:\python37\lib\site-packages (from xsrfprobe) (1.14.0)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python37\lib\site-packages (from requests->xsrfprobe) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\python37\lib\site-packages (from requests->xsrfprobe) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\python37\lib\site-packages (from requests->xsrfprobe) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python37\lib\site-packages (from requests->xsrfprobe) (1.25.10)
Requirement already satisfied: beautifulsoup4 in c:\python37\lib\site-packages (from bs4->xsrfprobe) (4.9.1)
Requirement already satisfied: soupsieve>1.2 in c:\python37\lib\site-packages (from beautifulsoup4->bs4->xsrfprobe) (2.0.1)

C:\Users\VZ>xsrfprobe --help
'xsrfprobe' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by 0xInfection** [comment]
@wadim-al have a look at the updated comment. I just realised that Windows PATH is not recursive.

**Comment by wadim-al** [comment]
@0xInfection Please check that Python is now correctly reinstalled and its output in the previous comment. 2 Paths were registered by the installer.

**Comment by 0xInfection** [comment]
Message me on Twitter @0xInfection, might have a bit of chat there.

**Comment by wadim-al** [comment]
Solution:
0. Make sure official standalone python is installed, PATH should have 2 paths to the interpreter and scripts, Windows aliases for python should be disabled in the control panel, If using the registry hack it should be 
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\InheritConsoleHandles 0`
1. On Windows 10 navigate to standalone python install at C:\Python37\Scripts
2. Copy xsrfprobe to xsrfprob.py (!!!note the different name (no 'e'), so no import error will be showing up)
3. Use xsrfprob now instead of what the docs mention.

Proposal:
I suspect Windows doesn't like xsrfprobe without extension, so It might worth trying building the package so it contains xsrfprobe.py instead of xsrfprobe, so Win cmd can see it properly. There might be an import error after renaming.
