### ISSUE TITLE
local variable 'value' referenced before assignment

### ISSUE THREAD

**Issue by CookiePackage** [0xInfection/XSRFProbe#49]
#### Describe the bug
While scanning a page, on Origin based request validation part it encounters an error while crafting inputs as form type.

#### Command You Used
xsrfprobe -u http://192.168.1.1/cgi-bin/luci/admin/ -c "sysauth=2065fe79a5b0a8ff9712cec650edd834" --crawl -v -t 10 -d 10 -o AnotherTest 

#### Full Stack Trace Error
![image](https://user-images.githubusercontent.com/73100455/96571211-f0a9ee80-12d3-11eb-8241-ff85ae987e74.png)

in errored.log file
![image](https://user-images.githubusercontent.com/73100455/96571266-00c1ce00-12d4-11eb-9529-2f08c96a1f14.png)

#### Environment:
- __OS__: [Ubuntu 20.04.1 LTS]
- __Python version__: [v3.8.5]

#### Some Questions

- [x] I am using the latest version of XSFRProbe.
- [x] I installed the dependecies using `pip3` instead of `pip`.
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

**Comment by prolexgreen** [comment]
I have the same issue!

**Comment by RobertABT** [comment]
I'm having the same issue, python 3.9.2 on kali 5.10.0-kali7-amd64
Log states:
(i) http://10.10.136.75/ -> local variable 'value' referenced before assignment

End of the output from running xsrfprobe -u 10.10.136.75 

[!] Parsing URL parameters...
 [!] Crafting inputs as form type...
 [*] Processing <input type="text" name="...

 [-] Encountered an error. 

 [-] Please view the error log files to view what went wrong.
 [-] local variable 'value' referenced before assignment

**Comment by 0xInfection** [comment]
This is being worked on the [fixes](https://github.com/0xInfection/XSRFProbe/tree/fixes) branch. I'll try to create a release asap.

**Comment by ucola** [comment]
Same issue here, any progress?

**Comment by JoonasMykkanen** [comment]
Did this ever get fixed? I just installed 3.2.1 with pip3 and I'm getting this issue with simple xsrfprobe -u http://xxx.xxx.xxx.xxx

**Comment by nrathaus** [comment]
I fixed it in my branch: https://github.com/nrathaus/XSRFProbe

Upstream project seems to have been abandoned
