### ISSUE TITLE
UnboundLocalError: local variable 'web' referenced before assignment

### ISSUE THREAD

**Issue by MYavuzYAGIS** [0xInfection/XSRFProbe#54]
#### Describe the bug
UnboundLocalError
#### Command You Used
xsrfprobe --malicious

#### Full Stack Trace Error
Traceback (most recent call last):
  File "/usr/local/bin/xsrfprobe", line 15, in <module>
    xsrfprobe.startEngine()
  File "/usr/local/lib/python3.9/site-packages/xsrfprobe/xsrfprobe.py", line 14, in startEngine
    main.Engine()  # start the Scanner Engine ;)
  File "/usr/local/lib/python3.9/site-packages/xsrfprobe/core/main.py", line 71, in Engine
    web, fld = inputin()  # Take the input
  File "/usr/local/lib/python3.9/site-packages/xsrfprobe/core/inputin.py", line 30, in inputin
    if 'http' not in web:  # add protocol to site
UnboundLocalError: local variable 'web' referenced before assignment

#### Environment:
Darwin myyagis 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

python 3.9.7

#### Some Questions

- [x] I am using the latest version of XSFRProbe.
- [x] I installed the dependecies using `pip3` instead of `pip`.
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

#### Other stuff
[Something else you want the author to know?]

**Comment by timeisflowing** [comment]
> #### Describe the bug
> 
> UnboundLocalError
> #### Command You Used
> 
> xsrfprobe --malicious
> #### Full Stack Trace Error
> 
> Traceback (most recent call last): File "/usr/local/bin/xsrfprobe", line 15, in xsrfprobe.startEngine() File "/usr/local/lib/python3.9/site-packages/xsrfprobe/xsrfprobe.py", line 14, in startEngine main.Engine() # start the Scanner Engine ;) File "/usr/local/lib/python3.9/site-packages/xsrfprobe/core/main.py", line 71, in Engine web, fld = inputin() # Take the input File "/usr/local/lib/python3.9/site-packages/xsrfprobe/core/inputin.py", line 30, in inputin if 'http' not in web: # add protocol to site UnboundLocalError: local variable 'web' referenced before assignment
> #### Environment:
> 
> Darwin myyagis 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
> 
> python 3.9.7
> #### Some Questions
> 
>     * [x]  I am using the latest version of XSFRProbe.
> 
>     * [x]  I installed the dependecies using `pip3` instead of `pip`.
> 
>     * [x]  I have read the documentation before submitting this issue.
> 
>     * [x]  I have checked the other issues to see if someone reported this before.
> 
> 
> #### Other stuff
> 
> [Something else you want the author to know?]
just a little check is required, change line 28 this script core/inputin.py..

`    try:
        if SITE_URL:
            web = SITE_URL  # If already assigned
        if not web.endswith('/'):
            web = web + '/'
        if 'http' not in web:  # add protocol to site
            web = 'http://' + web
    except Exception:
        pass`

**Comment by timeisflowing** [comment]
> #### Describe the bug
> 
> UnboundLocalError
> #### Command You Used
> 
> xsrfprobe --malicious
> #### Full Stack Trace Error
> 
> Traceback (most recent call last): File "/usr/local/bin/xsrfprobe", line 15, in xsrfprobe.startEngine() File "/usr/local/lib/python3.9/site-packages/xsrfprobe/xsrfprobe.py", line 14, in startEngine main.Engine() # start the Scanner Engine ;) File "/usr/local/lib/python3.9/site-packages/xsrfprobe/core/main.py", line 71, in Engine web, fld = inputin() # Take the input File "/usr/local/lib/python3.9/site-packages/xsrfprobe/core/inputin.py", line 30, in inputin if 'http' not in web: # add protocol to site UnboundLocalError: local variable 'web' referenced before assignment
> #### Environment:
> 
> Darwin myyagis 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
> 
> python 3.9.7
> #### Some Questions
> 
>     * [x]  I am using the latest version of XSFRProbe.
> 
>     * [x]  I installed the dependecies using `pip3` instead of `pip`.
> 
>     * [x]  I have read the documentation before submitting this issue.
> 
>     * [x]  I have checked the other issues to see if someone reported this before.
> 
> 
> #### Other stuff
> 
> [Something else you want the author to know?]
![change](https://user-images.githubusercontent.com/5330431/152696912-ccc11c66-25b1-44ff-82ff-6238d8b1335d.PNG)
Change script fix it this way inputin.py

**Comment by MYavuzYAGIS** [comment]
Thanks!
