### ISSUE TITLE
[Inquiry] Exception Caught: list index out of range Meaning

### ISSUE THREAD

**Issue by dennisarriola** [0xInfection/XSRFProbe#60]
Hello, 

I was trying to run this tool into one of our web applications and got an "Exception Caught: list index out of range" result. 
Our web application was installed in another PC and can be accessed using its IP via specific port.
If I include the port, the result is "Site seems to be down..." and if I exclude the port, I'll get "Exception Caught: list index out of range"
![Screenshot from 2024-04-09 00-54-09](https://github.com/0xInfection/XSRFProbe/assets/54200801/5f450acc-be60-4a1b-805c-71f21c090b8f)
![Screenshot from 2024-04-09 00-54-34](https://github.com/0xInfection/XSRFProbe/assets/54200801/f07f58e4-9afa-40d6-9a63-8d547547f93b)

Can someone help me figure out how to use this tool effectively?

Thank you very much.

**Comment by ymul100** [comment]
The same ...

**Comment by nrathaus** [comment]
Can you provide more context to the problem? if you can provide a sample site where this error occurs, the error can be fixed.

Example run:
```
xsrfprobe --url=https://demo.testfire.net:443/ --crawl --verbose
```

**Comment by ymul100** [comment]
> Can you provide more context to the problem? if you can provide a sample site where this error occurs, the error can be fixed.
> 
> Example run:
> 
> ```
> xsrfprobe --url=https://demo.testfire.net:443/ --crawl --verbose
> ```

If I use xsrfprobe --url=https://demo.testfire.net:443/ --crawl --verbose then 
I have 
[!] Testing site demo.testfire.net:443 status...
 [-] Site seems to be down...

If I use it as I used it before
xsrfprobe -u https://demo.testfire.net

I have it
 [!] Testing site demo.testfire.net status...
 [+] Site seems to be up!
 [-] Exception Caught: list index out of range
 
 I will add that it worked for 10 minutes at the beginning.

**Comment by ymul100** [comment]
Ok, works with xsrfprobe --url=[https://demo.testfire.net --crawl --verbose  :) without :443

Thank you

**Comment by nrathaus** [comment]
With and without `:443` should work
