### ISSUE TITLE
[Bug] => Shebang lines are hardcoded to legacy Python

### ISSUE THREAD

**Issue by cclauss** [0xInfection/XSRFProbe#8]
https://github.com/theInfectedDrake/XSRFProbe/search?p=2&q=python2&unscoped_q=python2

**Comment by 0xInfection** [comment]
Umhm, I am aware of this issue, and I will make make any changes to code after I merge your PR to avoid conflicts.

**Comment by 0xInfection** [comment]
Fixed in #7. :)
